# Server
server.port=8080
spring.application.name=gatekeeper-gateway

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Rate Limiting
gatekeeper.rate-limit.default-limit=${RATE_LIMIT_DEFAULT:100}
gatekeeper.rate-limit.default-window=${RATE_LIMIT_WINDOW:60s}
gatekeeper.rate-limit.key-prefix=rl

# Routes
gatekeeper.routes.definitions[0].id=demo-httpbin
gatekeeper.routes.definitions[0].prefix=/demo
gatekeeper.routes.definitions[0].target=https://httpbin.org

# Actuator
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=when-authorized
management.metrics.tags.application=${spring.application.name}

# Logging
logging.level.dev.devangsharma.gatekeeper=DEBUG
