# Server
server.port=8091
spring.application.name=gatekeeper-analytics

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

# Virtual Threads
spring.threads.virtual.enabled=true

# Logging
logging.level.dev.devangsharma.gatekeeper=DEBUG
